name: Python Black

on: [push, pull_request]

jobs:
  lint:
    name: Python Lint
    runs-on: ubuntu-latest
    steps:
      - name: Setup checkout
        uses: actions/checkout@master
      - name: Install uv
        uses: astral-sh/setup-uv@v7
      - name: Lint with Black
        run: uv run --extra dev black --check gunpowder tests
