name: Tests

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - master

jobs:
  test:
    name: ${{ matrix.platform }} (${{ matrix.python-version }})
    runs-on: ${{ matrix.platform }}
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.10", "3.11", "3.12" ]
        platform: [ ubuntu-latest ]

    steps:
      - uses: actions/checkout@v3

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: Run tests
        run: uv run --python=${{ matrix.python-version }} --group dev pytest -v --color
          yes --cov gunpowder --cov-report xml

      - uses: codecov/codecov-action@v3
